openapi: 3.0.3
info:
  title: YouTube API
  description: |-
    This API provides access to YouTube's core features, allowing developers to interact with videos, channels, playlists, comments, and analytics.
  termsOfService: https://www.youtube.com/t/terms
  contact:
    email: api-support@youtube.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Full documentation
  url: https://developers.google.com/youtube
servers:
  - url: https://www.googleapis.com/youtube/v3
tags:
  - name: video
    description: Operations related to video management (upload, update, delete, retrieve)
  - name: channel
    description: Access and manage YouTube channel
  - name: playlist
    description: Manage playlist and retrieve related data
  - name: comment
    description: Interact with video comment
paths:
  /video/{channelId}/{videoId}:
    get:
      summary: Selected video
      tags:
        - video
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/videoId'
      responses:
        '200':
          description: A video
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
    delete:
      summary: Delete a video
      tags:
       - video
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/videoId'
      responses:
        '200':
          description: The video was deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Video deleted successfully
  /video/{channelId}/{videoId}/update-statistics:
    put:
      summary: Update video statistics
      tags:
       - video
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/videoId'
      requestBody:
        description: New statistics
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  views:
                    type: integer
                    description: Updated number of views
                  likes:
                    type: integer
                    description: Updated number of likes
                  dislikes:
                    type: integer
                    description: Updated number of dislikes
                  comments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: Statistics have been successfully updated
        '400':
          description: Bad request
  /channel/{channelId}:
    get:
      summary: Retrieve channel information
      tags:
        - channel
      parameters:
        - $ref: '#/components/parameters/channelId'
      responses:
        '200':
          description: Channel information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
    delete:
      summary: Delete the channel
      tags:
        - channel
      parameters:
        - $ref: '#/components/parameters/channelId'
      responses:
        '200':
          description: The channel has been deleted
        '418':
          description: I don't know
  /channel/{channelId}/add-video:
    post:
      summary: Add new video
      tags:
        - channel
      parameters:
        - $ref: '#/components/parameters/channelId'
      requestBody:
        description: New video
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Video'
      responses:
        '200':
          description: The video has been added
        '418':
          description: I don't know
  /channel/{channelId}/update-countSubscribers:
    put:
      summary: Update count Subscribers
      tags:
       - channel
      parameters:
        - $ref: '#/components/parameters/channelId'
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: integer
      responses:
        '200':
          description: The number of subscribers has been updated
        '418':
          description: I don't know
  /playlist/{channelId}/{playlistId}:
    get:
      summary: Return a playlist
      tags:
        - playlist
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/playlistId'
      responses:
        '200':
          description: A playlist from the channel
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Playlist'
        '500':
          description: The playlist could not be found 
    post:
      summary: Add new video
      tags:
        - playlist
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/playlistId'
      requestBody:
        description: Id new video
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Video'
      responses:
        '200':
          description: The video has been added to the playlist
        '418':
          description: I don't know
    delete:
      summary: Delete playlist
      tags:
       - playlist
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/playlistId'
      responses:
        '200':
          description: The operation was successful
        '418':
          description: An unknown error occurred and the playlist was not deleted
  /playlist/{channelId}/{playlistId}/{videoId}::
    delete:
      summary: Delete video
      tags:
        - playlist
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/playlistId'
        - $ref: '#/components/parameters/videoId'
      responses:
        '200':
          description: The video has been removed from the playlist
        '418':
          description: I don't know
  /comment/{channelId}/{videoId}/all-comments:
    get:
      summary: Retrieve comments for a video
      tags:
        - comment
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/videoId'
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
  /comment/{channelId}/{videoId}:
    post:
      summary: Post a new comment on a video
      tags:
        - comment
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/videoId'
      requestBody:
        description: The content of the comment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          description: Comment posted successfully
        '418':
          description: I don't know
  /comment/{channelId}/{videoId}/{commentId}:
    delete:
      summary: Delete comments
      tags:
       - comment
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/videoId'
        - $ref: '#/components/parameters/commentId'
      responses:
        '200':
          description: The list of comments was deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Comments deleted successfully
  /comment/{channelId}/{videoId}/{commentId}/update-statistics:
    put:
      summary: Update comment statistics
      tags:
       - comment
      parameters:
        - $ref: '#/components/parameters/channelId'
        - $ref: '#/components/parameters/videoId'
        - $ref: '#/components/parameters/commentId'
      requestBody:
        description: New info
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                countLikes:
                  type: integer
                  example: 100
                countDizlikes:
                  type: integer
                  example: 100
                childComment:
                  type: object
                  example:
                    $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: The statistics have been updated
        '418':
          description: I don't know
components:
  parameters:
    videoId:
      name: videoId
      in: query
      description: The ID of the video
      required: true
      schema:
        type: string
    channelId:
      name: channelId
      in: query
      description: The ID of the channel
      required: true
      schema:
        type: string
    playlistId:
      name: playlistId
      in: query
      description: The ID of the playlist
      required: true
      schema:
        type: string
    commentId:
      name: commentId
      in: query
      description: The ID of the comment
      required: true
      schema:
        type: string
  schemas:
    Video:
      type: object
      properties:
        id:
          type: string
        channelId:
          type: string
        title:
          type: string
        description:
          type: string
        publishedAt:
          type: string
          format: date-time
        countLikes:
          type: integer
        countDizlikes:
          type: integer
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    Channel:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        countSubscribers:
          type: integer
        dateCreate:
          type: string
          format: date-time
        playLists:
          type: array
          items:
            $ref: '#/components/schemas/Playlist'
        videos:
          type: array
          items:
            $ref: '#/components/schemas/Video'
    Playlist:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        title:
          type: string
        description:
          type: string
        chanelId:
          type: string
        videos:
          type: array
          items:
            $ref: '#/components/schemas/Video'
    Comment:
      type: object
      properties:
        id:
          type: string
        chanelId:
          type: string
        videoId:
          type: string
        text:
          type: string
        author:
          type: string
        publishedAt:
          type: string
          format: date-time
        countLikes:
          type: integer
        countDizlikes:
          type: integer
        childComments:
          type: array
          items: 
            $ref: '#/components/schemas/Comment'
